site_name: TrueRoll Documentation

theme:
  name: readthedocs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - API Documentation: api.md
  - Contribute: contribute.md
  - Contact: contact.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true
